routes/web.php
<?php

/*Route::redirect('/', 'user/login');
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('verify-account/{code}', 'User\Auth\RegisterController@verifyAccount')->name('verify:account');

// User
Route::group(['prefix' => 'user',
    'namespace' => 'User'], function () {
    Route::group(['middleware' => ['guest:web']], function () {
    
    //login
    Route::get('login', ['as' => 'user:login', 'uses' => 'Auth\LoginController@getLogin']);
    Route::post('login', ['as' => 'post:user:login', 'uses' => 'Auth\LoginController@postLogin']);

    Route::get('redirect', ['as' => 'user:login:redirect', 'uses' => 'Auth\SocialAuthGoogleController@redirect']);

    Route::get('callback', ['as' => 'user:login:call', 'uses' => 'Auth\SocialAuthGoogleController@callback']);


    //sigup
    Route::get('register', ['as' => 'user:register', 'uses' => 'Auth\RegisterController@getRegister']);
    Route::post('register', ['as' => 'post:user:register', 'uses' => 'Auth\RegisterController@postRegister']);

     // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('user:forgot:password');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('post:user:forgot:password');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('user:reset:password');
        Route::post('password/reset/{id}', 'Auth\ResetPasswordController@reset')->name('post:user:reset:password');
    });

    Route::group(['middleware' => 'auth:web'], function () {

        Route::get('logout', ['as' => 'user:logout', 'uses' => 'Auth\LoginController@getLogout']);


        // user dashboard
        Route::get('dashboard', ['as' => 'user:dashboard', 'uses' => 'DashboardController@index']);

        Route::get('dashboard-user-second', 'DashboardController@getPosts')->name('dashboard-user-second:postdata');

        // user profile
        Route::resource('userprofile', 'ProfileController', ['only' => ['index', 'store']]);

        // user change password
        Route::get('user-change-password', ['as' => 'user:change:password', 'uses' => 'SettingsController@userChangePassword']);
        Route::post('user-change-password', ['as' => 'post:user:change:password', 'uses' => 'SettingsController@postUserChangePassword']);

        //book
        Route::get('book', ['as' => 'user:book', 'uses' => 'BookController@index']);

        Route::resource('issue-books', 'IssueBookController');

        //Route::get('stripe', 'StripePaymentController@stripe');
        
        Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');
    });
});



// Admin

Route::group(['prefix' => 'admin',
    'namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('login', ['as' => 'admin:login', 'uses' => 'LoginController@getLogin']);
        Route::post('login', ['as' => 'post:admin:login', 'uses' => 'LoginController@postLogin']);

        // Password Reset Routes...
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}', 'ResetPasswordController@reset')->name('post:admin:reset:password');

	});

  Route::get('password/user/{token}', 'UserPasswordController@showResetForm')->name('admin:user:password');
        Route::post('password/reset/{id}', 'UserPasswordController@reset')->name('post:admin:user:password');


	Route::group([
        'middleware' => 'auth:admin'
    ], function () {
        Route::get('logout', ['as' => 'admin:logout', 'uses' => 'LoginController@getLogout']);

        Route::get('dashboard', ['as' => 'admin:dashboard', 'uses' => 'DashboardController@index']);

         Route::get('dashboard-second', 'DashboardController@getPosts')->name('dashboard-second:postdata');


        Route::post('dashboard-request/update/book', 'DashboardController@updateBook')->name('dashboard-request:update:book');

        Route::resource('users', 'UserController');

        Route::resource('categorys', 'CategoryController');

        Route::resource('books', 'BookController');

        Route::resource('issuebooks', 'IssueBookController');

        Route::resource('issuebook-request', 'IssueBookRequestController');

        Route::post('issuebook-request/update/status', 'IssueBookRequestController@updateStatus')->name('issuebook-request:update:status');

        Route::resource('profile', 'ProfileController', ['only' => ['index', 'store']]);

        Route::get('change-password', ['as' => 'admin:change:password', 'uses' => 'SettingsController@adminChangePassword']);
        Route::post('change-password', ['as' => 'post:admin:change:password', 'uses' => 'SettingsController@postAdminChangePassword']);
     });
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $table = 'books';

    protected $fillable = [
    	'category_id', 'book_name', 'author_name', 'price'
    ];

    public function category(){
    	return $this->belongsTo(Category::class,'category_id','id');
    }

    public function issue_book(){
 		return $this->hasMany(IssueBook::class);
 	}



}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\Admin\Datatables\BookDatatableScope;
use App\Domain\Admin\Request\BookRequest;
use App\Models\Book;
use App\Models\Category;

class BookController extends Controller
{
    public function index(BookDatatableScope $datatable)
    {
    	 if (request()->ajax()) {
            return $datatable->query();
        }
    
    	return view('admin.books.index', [
    		'html' => $datatable->html(),
    	]);
    }

    public function create()
    {
    	$categorys = Category::query()->pluck('category_name','id');
    	return view('admin.books.add',compact('categorys'));
    }

    public function store(BookRequest $request)
    {
    	Book::create($request->persist());
        session()->flash('success', 'Book added Successfully.');
        return redirect(route('books.index'));
    }

    public function edit(Book $book)
    {	
    	$categorys = Category::query()->pluck('category_name','id');
    	return view('admin.books.edit',compact('categorys', 'book'));
    }	

    public function update(BookRequest $request, $id)
    {
        $book = Book::findorfail($id);
        $book->fill($request->persist())->save();
        session()->flash("success", 'Book Update Successfully.');

        return redirect()->route('books.index');
    }

    public function destroy(Book $book)
    {
        $book->delete();
        session()->flash("success", 'Book Deleted Successfully.');

        return redirect()->route('books.index');
    }
}

app/Http/Controllers/User/BookController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\User\Datatables\BookDatatableScope;


class BookController extends Controller
{
    public function index(BookDatatableScope $datatable)
    {
    	 if (request()->ajax()) {
            return $datatable->query();
        }
    
    	return view('user.books.index', [
    		'html' => $datatable->html(),
    	]);
    }
}

resources/views/admin/books/add.blade.php
@extends('admin.layout.index')

@section('title')
    Add Book
@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4>Add Book</h4><br>
                </div>
                <div class="grid-body no-border">
                    <div class="row">
                        <div class="col-xs-12">
                            {{ html()->form('POST', route('books.store'))->acceptsFiles()->open() }}
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="">Book Name</label>
                                    {{
                                        html()
                                            ->input('text', 'book_name', old('book_name'))
                                            ->class('form-control')
                                            ->placeholder('Book Name')
                                    }}
                                    <span class="error">{{ $errors->first('book_name') }}</span>
                                </div>

                                <div class="form-group">
                                    <label for="">Author Name</label>
                                    {{
                                        html()
                                            ->input('text', 'author_name', old('author_name'))
                                            ->class('form-control')
                                            ->placeholder('Author Name')
                                    }}
                                    <span class="error">{{ $errors->first('author_name') }}</span>
                                </div>

                                <div class="form-group">
                                    <label for="">Category</label>
                                    {{
                                        html()
                                            ->select('category', $categorys)
                                            ->id('category')
                                            ->class('form-control')
                                    }}
                                   
                                    <span class="error">{{ $errors->first('category') }}</span>
                                </div>

                                <div class="form-group">
                                    <label for="">Price</label>
                                    {{
                                        html()
                                            ->input('text', 'price', old('price'))
                                            ->class('form-control')
                                            ->placeholder('Price')
                                    }}
                                    <span class="error">{{ $errors->first('price') }}</span>
                                </div>
                               
                                <div class="form-group">
                                    <span class="edit-cancel-button-append"></span>
                                    <button class="btn btn-primary" type="submit">Add Book</button>
                                    <a class="btn btn-default" href="{{ route('books.index') }}">Cancel</a>
                                </div>
                            {{ html()->form()->close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/books/edit.blade.php
@extends('admin.layout.index')

@section('title')
    Edit Book
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
@stop

@section('content')
    <div class="page-title">
        <h3>Edit Book</h3>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    
                {{ html()->form('PUT', route('books.update', $book->getKey()))->open() }}
                {{ csrf_field() }}
                <div class="row">
                   
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Book Name</label>
                            {{
                                html()
                                    ->input('text', 'book_name', old('book_name', $book->book_name))
                                    ->class('form-control')
                                    ->placeholder('Book Name')
                            }}
                            <span class="error">{{ $errors->first('book_name') }}</span>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Author Name</label>
                            {{
                                html()
                                    ->input('text', 'author_name', old('author_name', $book->author_name))
                                    ->class('form-control')
                                    ->placeholder('Author Name')
                            }}
                            <span class="error">{{ $errors->first('author_name') }}</span>
                        </div>
                    </div>


                     <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Category</label>
                            <div class="droplist">
                                {{
                                html()
                                    ->select('category',$categorys, old('category', $book->category)  )
                                    ->class('form-control')
                            }}
                                <span class="error">{{ $errors->first('category') }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Price</label>
                            {{
                                html()
                                    ->input('text', 'price', old('price', $book->price))
                                    ->class('form-control')
                                    ->placeholder('Price')
                            }}
                            <span class="error">{{ $errors->first('price') }}</span>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Edit Book</button>
                            <a href="{{route('books.index')}}" class="btn btn-white">Cancel</a></div>
                    </div>
                </div>

                {{ html()->form()->close() }}
            </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/books/index.blade.php
@extends('admin.layout.index')

@section('title')
    Book List
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
@stop

@section('content')

<div class="page-title">
    <h3>Manage Book</h3>

 	<a href="{{ route('books.create') }}" class="btn btn-primary pull-right">Add Book</a>
</div>

<div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    {!! $html->table() !!}
                </div>
            </div>
        </div>
    </div>
@stop


@section('page-js')
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    {!! $html->scripts() !!}
@stop