routes/web.php
<?php

/*Route::redirect('/', 'user/login');
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('verify-account/{code}', 'User\Auth\RegisterController@verifyAccount')->name('verify:account');

// User
Route::group(['prefix' => 'user',
    'namespace' => 'User'], function () {
    Route::group(['middleware' => ['guest:web']], function () {
    
    //login
    Route::get('login', ['as' => 'user:login', 'uses' => 'Auth\LoginController@getLogin']);
    Route::post('login', ['as' => 'post:user:login', 'uses' => 'Auth\LoginController@postLogin']);

    Route::get('redirect', ['as' => 'user:login:redirect', 'uses' => 'Auth\SocialAuthGoogleController@redirect']);

    Route::get('callback', ['as' => 'user:login:call', 'uses' => 'Auth\SocialAuthGoogleController@callback']);


    //sigup
    Route::get('register', ['as' => 'user:register', 'uses' => 'Auth\RegisterController@getRegister']);
    Route::post('register', ['as' => 'post:user:register', 'uses' => 'Auth\RegisterController@postRegister']);

     // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('user:forgot:password');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('post:user:forgot:password');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('user:reset:password');
        Route::post('password/reset/{id}', 'Auth\ResetPasswordController@reset')->name('post:user:reset:password');
    });

    Route::group(['middleware' => 'auth:web'], function () {

        Route::get('logout', ['as' => 'user:logout', 'uses' => 'Auth\LoginController@getLogout']);


        // user dashboard
        Route::get('dashboard', ['as' => 'user:dashboard', 'uses' => 'DashboardController@index']);

        Route::get('dashboard-user-second', 'DashboardController@getPosts')->name('dashboard-user-second:postdata');

        // user profile
        Route::resource('userprofile', 'ProfileController', ['only' => ['index', 'store']]);

        // user change password
        Route::get('user-change-password', ['as' => 'user:change:password', 'uses' => 'SettingsController@userChangePassword']);
        Route::post('user-change-password', ['as' => 'post:user:change:password', 'uses' => 'SettingsController@postUserChangePassword']);

        //book
        Route::get('book', ['as' => 'user:book', 'uses' => 'BookController@index']);

        Route::resource('issue-books', 'IssueBookController');

        //Route::get('stripe', 'StripePaymentController@stripe');
        
        Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');
    });
});



// Admin

Route::group(['prefix' => 'admin',
    'namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('login', ['as' => 'admin:login', 'uses' => 'LoginController@getLogin']);
        Route::post('login', ['as' => 'post:admin:login', 'uses' => 'LoginController@postLogin']);

        // Password Reset Routes...
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}', 'ResetPasswordController@reset')->name('post:admin:reset:password');

	});

  Route::get('password/user/{token}', 'UserPasswordController@showResetForm')->name('admin:user:password');
        Route::post('password/reset/{id}', 'UserPasswordController@reset')->name('post:admin:user:password');


	Route::group([
        'middleware' => 'auth:admin'
    ], function () {
        Route::get('logout', ['as' => 'admin:logout', 'uses' => 'LoginController@getLogout']);

        Route::get('dashboard', ['as' => 'admin:dashboard', 'uses' => 'DashboardController@index']);

         Route::get('dashboard-second', 'DashboardController@getPosts')->name('dashboard-second:postdata');


        Route::post('dashboard-request/update/book', 'DashboardController@updateBook')->name('dashboard-request:update:book');

        Route::resource('users', 'UserController');

        Route::resource('categorys', 'CategoryController');

        Route::resource('books', 'BookController');

        Route::resource('issuebooks', 'IssueBookController');

        Route::resource('issuebook-request', 'IssueBookRequestController');

        Route::post('issuebook-request/update/status', 'IssueBookRequestController@updateStatus')->name('issuebook-request:update:status');

        Route::resource('profile', 'ProfileController', ['only' => ['index', 'store']]);

        Route::get('change-password', ['as' => 'admin:change:password', 'uses' => 'SettingsController@adminChangePassword']);
        Route::post('change-password', ['as' => 'post:admin:change:password', 'uses' => 'SettingsController@postAdminChangePassword']);
     });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
	protected $table = 'categorys';

    protected $fillable = [
 		'category_name', 'is_active'
 	]; 

 	public function books(){
 		return $this->hasMany(Book::class);
 	}
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\Admin\Datatables\CategoryDatatableScope;
use App\Models\Category;
use App\Models\Book;
use App\Domain\Admin\Request\CategoryRequest;
use Validator;

class CategoryController extends Controller
{
    public function index(CategoryDatatableScope $datatable)
    {	
    	if (request()->ajax()) {
            return $datatable->query();
        }

    	return view('admin.categorys.index',[
    		'html' => $datatable->html(),
    	]);
    }

    public function store(CategoryRequest $request)
    {  
        Category::create($request->persist());
        
        return response()->json(['success'=>'Data is successfully added']);

        return redirect(route('categorys.index'))->with('success', ['your message,here']);
    }

    public function edit(Category $category)
    {
        return view('admin.categorys.edit', compact('category'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $category = Category::findorfail($id);
        $category->fill($request->persist())->save();
        session()->flash("success", 'Category Update Successfully.');

        return redirect()->route('categorys.index');
    }

    public function destroy(Category $category)
    {
        $category->delete();
        session()->flash("success", 'Category Deleted Successfully.');

        return redirect()->route('categorys.index');
    }
}

resources/views/admin/categorys/edit.blade.php
@extends('admin.layout.index')

@section('title')
    Edit Category
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
@stop

@section('content')

    <div class="page-title">
        <h3>Edit Category</h3>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    @include('admin.shared.messages')

                    {{ html()->form('POST', route('categorys.update', $category->getKey()))->open() }}
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group">
                            <label for="">Name</label>
                            {{
                                html()
                                    ->input('text', 'category_name', old('category_name', $category->category_name))
                                    ->class('form-control')
                                    ->placeholder('Category Name')
                            }}
                            <span class="error">{{ $errors->first('category_name') }}</span>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Edit Category</button>
                            <a href="{{ route('categorys.index') }}" class="btn btn-default" type="reset">Cancel</a>
                        </div>
                    {{ html()->form()->close() }}
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/categorys/index.blade.php
@extends('admin.layout.index')

@section('title')
    Category List
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
 
@stop

@section('content')

<div class="page-title">
    <h3>Manage Category</h3>
</div>

<div class="container" id="modelcontent" style="padding-right: 30%;">
   
  <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal" id="add_data">Add Category</button>

  <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Category</h4> 
                </div>
                <div class="modal-body">
                    <div class="tiers">
                        <div class="grid-body no-border">
                            <div class="row">
                                <div class="col-xs-12 add-tier-form">
                                    {{ html()->form('POST')->id('cat_add')->class('add-shifts-form')->acceptsFiles()->open() }}
                                    {{ csrf_field() }}
                                    <div class="form-group">
                                        <label for="">Category Name</label>
                                        {{
                                            html()
                                            ->input('text', 'category_name', old('category_name'))
                                            ->class('form-control')->id('category_name')->attribute('required')
                                            ->placeholder('Category Name')
                                        }}
                                        <span class="error">{{ $errors->first('category_name') }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                       <span class="edit-cancel-button-append"></span>
                        <input type="submit" name="submit" id="action" value="Add Category" class="btn btn-info add-tier-btn enableOnInput">
                        <button type="button" class="btn btn-default custom-btn" data-dismiss="modal">close</button>
                    </div>
                    {{ html()->form()->close() }}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="grid simple">
            <div class="grid-body no-border">
                {!! $html->table() !!}
            </div>
        </div>
    </div>
</div>
@stop

 @section('page-js')

<script type="text/javascript">

    $(document).ready(function(){
        $("#action").click(function(e){
            e.preventDefault();
            var category_name = $("#category_name").val();
            $.ajax({
                type: "POST",
                url: "{{ route('categorys.store') }}",             
                data: {category_name: category_name, _token: '{{csrf_token()}}' },
                success: function(response){ 
                    //$("#myModal").modal('hide');
                    //$(".modal-backdrop.in").hide();
                    swal("Success", "Category added successfully!", "success");
                   location.reload(true);
                }
            });
            return false;
        });
    });
</script>
  
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    {!! $html->scripts() !!}
@stop