routes/web.php
<?php

/*Route::redirect('/', 'user/login');
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('verify-account/{code}', 'User\Auth\RegisterController@verifyAccount')->name('verify:account');

// User
Route::group(['prefix' => 'user',
    'namespace' => 'User'], function () {
    Route::group(['middleware' => ['guest:web']], function () {
    
    //login
    Route::get('login', ['as' => 'user:login', 'uses' => 'Auth\LoginController@getLogin']);
    Route::post('login', ['as' => 'post:user:login', 'uses' => 'Auth\LoginController@postLogin']);

    Route::get('redirect', ['as' => 'user:login:redirect', 'uses' => 'Auth\SocialAuthGoogleController@redirect']);

    Route::get('callback', ['as' => 'user:login:call', 'uses' => 'Auth\SocialAuthGoogleController@callback']);


    //sigup
    Route::get('register', ['as' => 'user:register', 'uses' => 'Auth\RegisterController@getRegister']);
    Route::post('register', ['as' => 'post:user:register', 'uses' => 'Auth\RegisterController@postRegister']);

     // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('user:forgot:password');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('post:user:forgot:password');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('user:reset:password');
        Route::post('password/reset/{id}', 'Auth\ResetPasswordController@reset')->name('post:user:reset:password');
    });

    Route::group(['middleware' => 'auth:web'], function () {

        Route::get('logout', ['as' => 'user:logout', 'uses' => 'Auth\LoginController@getLogout']);


        // user dashboard
        Route::get('dashboard', ['as' => 'user:dashboard', 'uses' => 'DashboardController@index']);

        Route::get('dashboard-user-second', 'DashboardController@getPosts')->name('dashboard-user-second:postdata');

        // user profile
        Route::resource('userprofile', 'ProfileController', ['only' => ['index', 'store']]);

        // user change password
        Route::get('user-change-password', ['as' => 'user:change:password', 'uses' => 'SettingsController@userChangePassword']);
        Route::post('user-change-password', ['as' => 'post:user:change:password', 'uses' => 'SettingsController@postUserChangePassword']);

        //book
        Route::get('book', ['as' => 'user:book', 'uses' => 'BookController@index']);

        Route::resource('issue-books', 'IssueBookController');

        //Route::get('stripe', 'StripePaymentController@stripe');
        
        Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');
    });
});



// Admin

Route::group(['prefix' => 'admin',
    'namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('login', ['as' => 'admin:login', 'uses' => 'LoginController@getLogin']);
        Route::post('login', ['as' => 'post:admin:login', 'uses' => 'LoginController@postLogin']);

        // Password Reset Routes...
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}', 'ResetPasswordController@reset')->name('post:admin:reset:password');

	});

  Route::get('password/user/{token}', 'UserPasswordController@showResetForm')->name('admin:user:password');
        Route::post('password/reset/{id}', 'UserPasswordController@reset')->name('post:admin:user:password');


	Route::group([
        'middleware' => 'auth:admin'
    ], function () {
        Route::get('logout', ['as' => 'admin:logout', 'uses' => 'LoginController@getLogout']);

        Route::get('dashboard', ['as' => 'admin:dashboard', 'uses' => 'DashboardController@index']);

         Route::get('dashboard-second', 'DashboardController@getPosts')->name('dashboard-second:postdata');


        Route::post('dashboard-request/update/book', 'DashboardController@updateBook')->name('dashboard-request:update:book');

        Route::resource('users', 'UserController');

        Route::resource('categorys', 'CategoryController');

        Route::resource('books', 'BookController');

        Route::resource('issuebooks', 'IssueBookController');

        Route::resource('issuebook-request', 'IssueBookRequestController');

        Route::post('issuebook-request/update/status', 'IssueBookRequestController@updateStatus')->name('issuebook-request:update:status');

        Route::resource('profile', 'ProfileController', ['only' => ['index', 'store']]);

        Route::get('change-password', ['as' => 'admin:change:password', 'uses' => 'SettingsController@adminChangePassword']);
        Route::post('change-password', ['as' => 'post:admin:change:password', 'uses' => 'SettingsController@postAdminChangePassword']);
     });
});

app/Models/IssueBook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class IssueBook extends Model
{
    protected $table = 'issue_books';

    protected $fillable = [
    	'user_id', 'book_id', 'issue_date', 'expiry_date', 'retn_book'
    ];

    public function book(){
    	return $this->belongsTo(Book::class,'book_id','id');
    }

    public function user(){
    	return $this->belongsTo(User::class,'user_id','id');
    }

    public function bookrequests(){
        return $this->hasMany(RequestIssueBook::class);
    }
}

app/Http/Controllers/Admin/IssueBookController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\User;
use App\Models\AdminUser;
use App\Models\IssueBook;
use App\Models\RequestIssueBook;
use App\Domain\Admin\Datatables\IssueBookDatatableScope;
use App\Domain\Admin\Request\IssueBookRequest;

class IssueBookController extends Controller
{
    public function index(IssueBookDatatableScope $datatable)
    {
    	 if (request()->ajax()) {
            return $datatable->query();
        }

    	return view('admin.issuebooks.index', [
    		'html' => $datatable->html(),
    	]);
    }

    public function create()
    {
    	$books = Book::query()->pluck('book_name','id');
    	$users = User::query()->pluck('name','id');
    	return view('admin.issuebooks.add',compact('books', 'users'));
    }

    public function store(IssueBookRequest $request)
    {
        $issue_book = IssueBook::create($request->persist());
        RequestIssueBook::create(['issuebook_id' => $issue_book->id,'status' => 'approved' ]);

        session()->flash('success', 'Issue Book added Successfully.');
        return redirect(route('issuebooks.index'));
    }

    public function edit($id)
    {	
    	$issuebook = IssueBook::findorfail($id);
    	$books = Book::query()->pluck('book_name','id');
    	$users = User::query()->pluck('name','id');

    	return view('admin.issuebooks.edit',compact('books', 'issuebook', 'users'));
    }	

    public function update(IssueBookRequest $request, $id)
    {	
        $issuebook = IssueBook::findorfail($id);
        $issuebook->fill($request->persist())->save();
        session()->flash("success", 'Issue Book Update Successfully.');

        return redirect()->route('issuebooks.index');
    }

    public function destroy($id)
    {	
    	$issuebook = IssueBook::findorfail($id);
        $issuebook->delete();
        session()->flash("success", 'Issue Book Deleted Successfully.');

        return redirect()->route('issuebooks.index');
    }
}

app/Http/Controllers/User/IssueBookController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\User\Datatables\IssueBookDatatableScope;
use App\Models\Book;
use App\Models\User;
use App\Models\IssueBook;
use App\Models\RequestIssueBook;
use App\Domain\User\Request\IssueBookRequest;

class IssueBookController extends Controller
{

	public function __construct()
    {
        $this->middleware('web');
    }

    public function index(IssueBookDatatableScope $datatable)
    {
    	 if (request()->ajax()) {
            return $datatable->query();
        }
    
    	return view('user.issuebooks.index', [
    		'html' => $datatable->html(),
    	]);
    }

    public function create()
    {
    	$books = Book::query()->pluck('book_name','id');
    	$users = User::query()->pluck('name','id');
    	return view('user.issuebooks.add',compact('books', 'users'));
    }

    public function store(IssueBookRequest $request)
    {   
    	$issue_book = IssueBook::create($request->persist());
        RequestIssueBook::create(['issuebook_id' => $issue_book->id,'status' => 'pending' ]);
        session()->flash('success', 'Pls Approve Your Book.');
        return redirect(route('issue-books.index'));
    }
}

resources/views/admin/issuebooks/add.blade.php
@extends('admin.layout.index')

@section('title')
    Add Issue Book
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="grid simple">
            <div class="grid-title no-border">
                <h4>Add Issue Book</h4><br>
            </div>
            <div class="grid-body no-border">
                <div class="row">
                    <div class="col-xs-12">
                        {{ html()->form('POST', route('issuebooks.store'))->acceptsFiles()->open() }}
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="">User Name</label>
                            {{
                                html()
                                    ->select('user', $users)
                                    ->id('user')
                                    ->class('form-control')
                            }}
                            <span class="text-danger">{{ $errors->first('user') }}</span>
                        </div>
                        
                        <div class="form-group">
                            <label for="">Book Name</label>
                            {{
                                html()
                                    ->select('book', $books)
                                    ->id('book')
                                    ->class('form-control')
                            }}
                            <span class="text-danger">{{ $errors->first('book') }}</span>
                        </div>

                        <div class="form-group">
                            <label for="">Issue Date</label>
                            <div class="input-with-icon right">
                                {{
                                    html()
                                    ->input('text', 'issue_date')
                                    ->class('form-control datepicker')
                                    ->placeholder('yyyy-mm-dd')
                                    }}
                                <span class="text-danger">{{ $errors->first('issue_date') }}</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">Expiry Date</label>
                            <div class="input-with-icon right">
                                {{
                                    html()
                                    ->input('text', 'expiry_date')
                                    ->class('form-control datepicker')
                                    ->placeholder('yyyy-mm-dd')
                                    }}
                                <span class="text-danger">{{ $errors->first('expiry_date') }}</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="edit-cancel-button-append"></span>
                            <button class="btn btn-primary" type="submit">Issue Book</button>
                            <a class="btn btn-default" href="{{ route('issuebooks.index') }}">Cancel</a>
                        </div>
                        {{ html()->form()->close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('page-js')
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

   
    <script>
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: false
        });
    </script>
@stop

resources/views/admin/issuebooks/edit.blade.php
@extends('admin.layout.index')

@section('title')
    Edit Issue Book
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">
@stop


@section('content')
    <div class="page-title">
        <h3>Edit Issue Book</h3>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    
                {{ html()->form('PUT', route('issuebooks.update', $issuebook->getKey()))->open() }}
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">User Name</label>
                            <div class="droplist">
                                {{
                                html()
                                    ->select('user',$users, old('user', $issuebook->user))
                                    ->class('form-control')
                            }}
                                <span class="error">{{ $errors->first('user') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Book Name</label>
                            <div class="droplist">
                                {{
                                html()
                                    ->select('book',$books, old('book', $issuebook->book)  )
                                    ->class('form-control')
                            }}
                                <span class="error">{{ $errors->first('book') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Issue Date</label>
                            <div class="input-with-icon right">
                                {{
                                    html()
                                    ->input('text', 'issue_date', old('issue_date', $issuebook->issue_date))
                                    ->class('form-control datepicker')
                                    ->placeholder('yyyy-mm-dd')
                                    }}

                                <span class="text-danger">{{ $errors->first('issue_date') }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label">Expiry Date</label>
                            <div class="input-with-icon right">
                                {{
                                    html()
                                    ->input('text', 'expiry_date', old('expiry_date', $issuebook->expiry_date))
                                    ->class('form-control datepicker')
                                    ->placeholder('yyyy-mm-dd')
                                    }}

                                <span class="text-danger">{{ $errors->first('expiry_date') }}</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-12">
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Edit Issue Book</button>
                            <a href="{{route('issuebooks.index')}}" class="btn btn-white">Cancel</a></div>
                    </div>
                </div>
                {{ html()->form()->close() }}
            </div>
        </div>
    </div>
</div>
@stop

@section('page-js')
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

   
    <script>
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: false
        });
    </script>
@stop

resources/views/admin/issuebooks/index.blade.php
@extends('admin.layout.index')

@section('title')
    Issue Book List
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
@stop

@section('content')

<div class="page-title">
    <h3>Manage Issue Book</h3>

 	<a href="{{ route('issuebooks.create') }}" class="btn btn-primary pull-right">Add Issue Book</a>
</div>

<div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    {!! $html->table() !!}
                </div>
            </div>
        </div>
    </div>
@stop


@section('page-js')
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    {!! $html->scripts() !!}
@stop