routes/web.php
<?php

/*Route::redirect('/', 'user/login');
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('verify-account/{code}', 'User\Auth\RegisterController@verifyAccount')->name('verify:account');

// User
Route::group(['prefix' => 'user',
    'namespace' => 'User'], function () {
    Route::group(['middleware' => ['guest:web']], function () {
    
    //login
    Route::get('login', ['as' => 'user:login', 'uses' => 'Auth\LoginController@getLogin']);
    Route::post('login', ['as' => 'post:user:login', 'uses' => 'Auth\LoginController@postLogin']);

    Route::get('redirect', ['as' => 'user:login:redirect', 'uses' => 'Auth\SocialAuthGoogleController@redirect']);

    Route::get('callback', ['as' => 'user:login:call', 'uses' => 'Auth\SocialAuthGoogleController@callback']);


    //sigup
    Route::get('register', ['as' => 'user:register', 'uses' => 'Auth\RegisterController@getRegister']);
    Route::post('register', ['as' => 'post:user:register', 'uses' => 'Auth\RegisterController@postRegister']);

     // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('user:forgot:password');
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('post:user:forgot:password');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('user:reset:password');
        Route::post('password/reset/{id}', 'Auth\ResetPasswordController@reset')->name('post:user:reset:password');
    });

    Route::group(['middleware' => 'auth:web'], function () {

        Route::get('logout', ['as' => 'user:logout', 'uses' => 'Auth\LoginController@getLogout']);


        // user dashboard
        Route::get('dashboard', ['as' => 'user:dashboard', 'uses' => 'DashboardController@index']);

        Route::get('dashboard-user-second', 'DashboardController@getPosts')->name('dashboard-user-second:postdata');

        // user profile
        Route::resource('userprofile', 'ProfileController', ['only' => ['index', 'store']]);

        // user change password
        Route::get('user-change-password', ['as' => 'user:change:password', 'uses' => 'SettingsController@userChangePassword']);
        Route::post('user-change-password', ['as' => 'post:user:change:password', 'uses' => 'SettingsController@postUserChangePassword']);

        //book
        Route::get('book', ['as' => 'user:book', 'uses' => 'BookController@index']);

        Route::resource('issue-books', 'IssueBookController');

        //Route::get('stripe', 'StripePaymentController@stripe');
        
        Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');
    });
});



// Admin

Route::group(['prefix' => 'admin',
    'namespace' => 'Admin'], function () {
    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('login', ['as' => 'admin:login', 'uses' => 'LoginController@getLogin']);
        Route::post('login', ['as' => 'post:admin:login', 'uses' => 'LoginController@postLogin']);

        // Password Reset Routes...
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}', 'ResetPasswordController@reset')->name('post:admin:reset:password');

	});

  Route::get('password/user/{token}', 'UserPasswordController@showResetForm')->name('admin:user:password');
        Route::post('password/reset/{id}', 'UserPasswordController@reset')->name('post:admin:user:password');


	Route::group([
        'middleware' => 'auth:admin'
    ], function () {
        Route::get('logout', ['as' => 'admin:logout', 'uses' => 'LoginController@getLogout']);

        Route::get('dashboard', ['as' => 'admin:dashboard', 'uses' => 'DashboardController@index']);

         Route::get('dashboard-second', 'DashboardController@getPosts')->name('dashboard-second:postdata');


        Route::post('dashboard-request/update/book', 'DashboardController@updateBook')->name('dashboard-request:update:book');

        Route::resource('users', 'UserController');

        Route::resource('categorys', 'CategoryController');

        Route::resource('books', 'BookController');

        Route::resource('issuebooks', 'IssueBookController');

        Route::resource('issuebook-request', 'IssueBookRequestController');

        Route::post('issuebook-request/update/status', 'IssueBookRequestController@updateStatus')->name('issuebook-request:update:status');

        Route::resource('profile', 'ProfileController', ['only' => ['index', 'store']]);

        Route::get('change-password', ['as' => 'admin:change:password', 'uses' => 'SettingsController@adminChangePassword']);
        Route::post('change-password', ['as' => 'post:admin:change:password', 'uses' => 'SettingsController@postAdminChangePassword']);
     });
});

app/Models/User.php
<?php

namespace App\Models;

//use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'google_id', 'birth_date', 'is_active', 'verification_code', 'is_verified', 'forgot_password_token', 'user_password_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function isbook(){
        return $this->hasMany(IssueBook::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\Admin\Datatables\UserDatatableScope;
use App\Models\User;
use App\Domain\Admin\Request\UpdateUserRequest;
use App\Domain\Admin\Request\UserRequest;
use App\Domain\Util\MailUtility;
use Carbon\Carbon;

class UserController extends Controller
{
    public function index(UserDatatableScope $datatable)
    {
    	if (request()->ajax()) {
            return $datatable->query();
        }

    	return view('admin.users.index', [
    		'html' => $datatable->html(),
    	]);
    }

    public function create()
    {
        return view('admin.users.add');
    }

    public function store(UserRequest $request)
    {  
        $user = User::create($request->persist());
        
        $token = str_random(20). time();

        if($user->fill([
            'user_password_token' => $token
        ])->save()){

        $data = [
            'name' => $user->name,
            'link' => route('admin:user:password', $token)
        ];
        (new MailUtility())->sendMail('admin.emails.user-password', $data, $request->get('email'), 'Your Pasword.');
        session()->flash('success', 'password link sent to your email.');

        session()->flash('success', 'User Added Successfully.');
        return redirect(route('users.index'));
        }
    }

    public function edit(User $user)
    {
    	return view('admin.users.edit', compact('user'));
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $user = User::findorfail($id);
        $user->fill($request->persist())->save();
        session()->flash('success', 'User Updated Successfully.');

        return redirect()->route('users.index');
    }

    public function destroy(User $user)
    {
        $user->delete();
        session()->flash('success', 'User Deleted Successfully.');

        return redirect()->route('users.index');
    }
}

app/Http/Controllers/User/BookController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\User\Datatables\BookDatatableScope;


class BookController extends Controller
{
    public function index(BookDatatableScope $datatable)
    {
    	 if (request()->ajax()) {
            return $datatable->query();
        }
    
    	return view('user.books.index', [
    		'html' => $datatable->html(),
    	]);
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Book;
use App\Models\IssueBook;
use Carbon\Carbon;
use App\Domain\User\Datatables\DashboardDatatableScope;

class DashboardController extends Controller
{
    public function index(DashboardDatatableScope $datatable)
    {
        if (request()->ajax()) {
            return $datatable->query();
        }

        $totalBooks = Book::count();

       // $query = auth()->user()->isbook()->with(['book','user'])->count();

        $total_issuebook =  auth()->user()->isbook()->with(['book','user'])->where('retn_book', '=', 'pending')->count();        

        $carbon = Carbon::today();
        $format = $carbon->format('Y-m-d');

        return view('user.dashboard.dashboard', compact('totalBooks', 'total_issuebook', 'format'),[
            'html' => $datatable->html()
        ]);
    }

    public function getPosts()
    {
        return \DataTables::of(auth()->user()->isbook()->with(['book','user'])->where('retn_book', '=', 'pending'))->make(true);
    }
}

app/Http/Controllers/User/IssueBookController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\User\Datatables\IssueBookDatatableScope;
use App\Models\Book;
use App\Models\User;
use App\Models\IssueBook;
use App\Models\RequestIssueBook;
use App\Domain\User\Request\IssueBookRequest;

class IssueBookController extends Controller
{

	public function __construct()
    {
        $this->middleware('web');
    }

    public function index(IssueBookDatatableScope $datatable)
    {
    	 if (request()->ajax()) {
            return $datatable->query();
        }
    
    	return view('user.issuebooks.index', [
    		'html' => $datatable->html(),
    	]);
    }

    public function create()
    {
    	$books = Book::query()->pluck('book_name','id');
    	$users = User::query()->pluck('name','id');
    	return view('user.issuebooks.add',compact('books', 'users'));
    }

    public function store(IssueBookRequest $request)
    {   
    	$issue_book = IssueBook::create($request->persist());
        RequestIssueBook::create(['issuebook_id' => $issue_book->id,'status' => 'pending' ]);
        session()->flash('success', 'Pls Approve Your Book.');
        return redirect(route('issue-books.index'));
    }
}

app/Http/Controllers/User/ProfileController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\User\Request\ProfileRequest;
use App\Models\User;

class ProfileController extends Controller
{
    public function index()
    {
    	$user = auth('web')->user();

    	return view('user.users.profile', compact('user'));
    }

    public function store(ProfileRequest $request)
    {
    	$user = auth('web')->user();
    	$user->fill($request->persist())->save();
    	session()->flash('success', 'User Profile updated successfully!.');

    	return back();
    }
}

app/Http/Controllers/User/SettingsController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Domain\User\Request\ChangePasswordRequest;

class SettingsController extends Controller
{
    public function userChangePassword()
	{
		return view('user.settings.change-password');
	}

	public function postUserChangePassword(ChangePasswordRequest $request)
	{
		$user = auth('web')->user();
		if(!auth()->attempt(['email' => $user->email, 'password' => $request->get('current_password')])) {
			session()->flash('error', 'Current password does not match!.');

			return back();
		}

		$user->fill([
			'password' => bcrypt($request->get('password'))
		])->save();
		session()->flash('success', 'Password changed successfully!.');

		return back();
	}
}

app/Http/Controllers/User/StripePaymentController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\User;
use Session;
use Stripe;
use App\Models\Charge;

class StripePaymentController extends Controller
{
    public function stripePost(Request $request)
    {
        Stripe::setApiKey(env('STRIPE_SECRET'));
 
        $token = request('stripeToken');
 
        $charge = Charge::create([
            'amount' => 1000,
            'currency' => 'usd',
            'description' => 'Test Book',
            'source' => $token,
        ]);
  
        Session::flash('success', 'Payment successful!');
          
       // return redirect()->back();

        $books = Book::query()->pluck('book_name','id');
        $users = User::query()->pluck('name','id');

        return view('user.issuebooks.add',compact('books', 'users'));
    }
}

resources/views/admin/users/add.blade.php
@extends('admin.layout.index')

@section('title')
    Add User
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="grid simple">
            <div class="grid-title no-border">
                <h4>Add New User</h4><br>
            </div>
            <div class="grid-body no-border">
                <div class="row">
                    <div class="col-xs-12">

                        {{ html()->form('POST', route('users.store'))->acceptsFiles()->open() }}
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="">Name</label>
                                {{
                                    html()
                                        ->input('text', 'name', old('name'))
                                        ->class('form-control')
                                        ->placeholder('User Name')
                                }}
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            </div>

                            <div class="form-group">
                                <label for="">Email</label>
                                {{
                                    html()
                                        ->input('text', 'email', old('email'))
                                        ->class('form-control')
                                        ->placeholder('Email')
                                }}
                                <span class="text-danger">{{ $errors->first('email') }}</span>
                            </div>

                            <div class="form-group"><label for="">Birth Date</label>
                                {{
                                    html()
                                    ->input('text', 'birth_date')
                                    ->class('form-control datepicker')
                                    ->placeholder('yyyy-mm-dd')
                                    }}
                                <span class="text-danger">{{ $errors->first('birth_date') }}</span>
                            </div>

                            <div class="form-group">
                                <span class="edit-cancel-button-append"></span>
                                <button class="btn btn-primary" type="submit">Add User</button>
                                <a class="btn btn-default" href="{{ route('users.index') }}">Cancel</a>
                            </div>
                        {{ html()->form()->close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('page-js')

    <script>
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: false
        });
    </script>
@stop

resources/views/admin/users/edit.blade.php
@extends('admin.layout.index')

@section('title')
    Edit User
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css">
@stop

@section('content')
    <div class="page-title">
        <h3>Edit User</h3>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    @include('admin.shared.messages')

                    {{ html()->form('POST', route('users.update', $user->getKey()))->open() }}
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="form-group">
                            <label for="">Name</label>
                            {{
                                html()
                                    ->input('text', 'name', old('name', $user->name))
                                    ->class('form-control')
                                    ->placeholder('Name')
                            }}
                            <span class="error">{{ $errors->first('name') }}</span>
                        </div>

                        <div class="form-group">
                            <label for="">Email</label>
                            {{
                                html()
                                    ->input('email', 'email', old('email', $user->email))
                                    ->class('form-control')
                                    ->placeholder('Email')
                            }}
                            <span class="error">{{ $errors->first('email') }}</span>
                        </div>

                        <div class="form-group">
                            <label for="">Birth Date</label>
                             {{
                                    html()
                                    ->input('text', 'birth_date', old('birth_date', $user->birth_date))
                                    ->class('form-control datepicker')
                                    ->placeholder('yyyy-mm-dd')
                                    }}
                            <span class="text-danger">{{ $errors->first('birth_date') }}</span>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Edit User</button>
                            <a href="{{ route('users.index') }}" class="btn btn-default" type="reset">Cancel</a>
                        </div>
                    {{ html()->form()->close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('page-js')
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

    <script>
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: false
        });
    </script>
@stop

resources/views/admin/users/index.blade.php
@extends('admin.layout.index')

@section('title')
    Users List
@stop

@section('page-css')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
   
@stop

@section('content')
    <div class="page-title">
        <h3>Manage Users</h3>
    
        <a href="{{ route('users.create') }}" class="btn btn-primary pull-right">Add User</a>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-body no-border">
                    {!! $html->table() !!}
                </div>
            </div>
        </div>
    </div>
@stop

@section('page-js')
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    {!! $html->scripts() !!}
@stop

resources/views/admin/users/profile.blade.php
@extends('admin.layout.index')

@section('title')
    Profile
@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h3>Edit Profile</h3>
                </div>
                <div class="grid-body no-border">
                    <div class="row">
                        <div class="col-xs-12">
                            {{ html()->form('POST', route('profile.store'))->open() }}
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="">Name</label>
                                    {{
                                        html()
                                            ->text('name', old('name', $user->username))
                                            ->class('form-control')
                                            ->placeholder('Name')
                                    }}
                                    <span class="error">{{ $errors->first('name') }}</span>
                                </div>

                                <div class="form-group">
                                    <label for="">Email</label>
                                    {{
                                        html()
                                            ->email('email', old('email', $user->email))
                                            ->class('form-control')
                                            ->placeholder('Email')
                                    }}
                                    <span class="error">{{ $errors->first('email') }}</span>
                                </div>

                                <div class="form-group">
                                    <span class="edit-cancel-button-append"></span>
                                    <button class="btn btn-primary" type="submit">Update Profile</button>
                                </div>
                            {{ html()->form()->close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop